language: cpp

os:
  - linux
  - osx

compiler:
 - clang
 - gcc

matrix:
  exclude:
     - os: osx
       compiler: gcc
     - os: linux
       compiler: clang

sudo: false

env:
  matrix:
   - NODE_VERSION="0.10.36"
   - NODE_VERSION="0.12.0"
   - NODE_VERSION="iojs-v1.2.0"
  global:
   - secure: KitzGZjoDblX/3heajcvssGz0JnJ/k02dr2tu03ksUV+6MogC3RSQudqyKY57+f8VyZrcllN/UOlJ0Q/3iG38Oz8DljC+7RZxtkVmE1SFBoOezKCdhcvWM12G3uqPs7hhrRxuUgIh0C//YXEkulUrqa2H1Aj2xeen4E3FAqEoy0=
   - secure: WLGmxl6VTVWhXGm6X83GYNYzPNsvTD+9usJOKM5YBLAdG7cnOBQBNiCCUKc9OZMMZVUr3ec2/iigakH5Y8Yc+U6AlWKzlORyqWLuk4nFuoedu62x6ocQkTkuOc7mHiYhKd21xTGMYauaZRS6kugv4xkpGES2UjI2T8cjZ+LN2jU=

before_install:
# check if tag exists and matches package.json
- scripts/validate_tag.sh
# get commit message
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
# put node-pre-gyp on path
- export PATH=./node_modules/.bin/:$PATH
# here we set up the node version on the fly based on the matrix value.
# This is done manually so that it is easy to flip the 'language' to
# objective-c in another branch (to run the same travis.yml on OS X)
- rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- node --version
- npm --version
- which node
- if [[ `uname -s` == 'Darwin' ]]; then brew install pkg-config; fi
- if [[ `uname -s` == 'Linux' ]]; then
    git clone --depth 1 https://github.com/mapbox/mason.git ./.mason;
    export MASON_DIR=$(pwd)/.mason;
    ./mason/mason install cmake 3.2.2;
    export PATH=$(~/.mason/mason prefix cmake 3.2.2)/bin:$PATH;
  fi;

install:
# set a few env settings for the static build script
- NODE_MODULE_ROOT=`pwd`
- export OSRM_RELEASE="v4.5.0"
# WARNING: this script modifies the environment
- source ./scripts/static_build.sh
# reset nvm version otherwise now one pre-installed by travis
# on the homebrew path may be picked up instead
- source ~/.nvm/nvm.sh
- echo $NODE_VERSION
- which node
- node --version
- npm --version
- set +u
- nvm use $NODE_VERSION || true
- which node
- node --version
- npm --version
- cd ${NODE_MODULE_ROOT}

before_script:
- if [[ `uname -s` == 'Darwin' ]]; then otool -L ./lib/binding/* || true; fi
- if [[ `uname -s` == 'Linux' ]]; then readelf -d ./lib/binding/* || true; fi
- which osrm-extract||true;rm -rf ${TMP_DEPS_DIR};which osrm-extract||true;
- make test

script:
# now we publish the binary, if requested
- PUBLISH_BINARY=false
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then echo PUBLISH_BINARY;PUBLISH_BINARY=true; fi;
# Note: this publishing is done here, in the 'script' section, instead of the 'after_success'
# since we want any failure here to stop the build immediately
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish; fi
# now clean up to prepare to re-install from remote binary
- node-pre-gyp clean
# now install from published binary
# Note: we capture the error here so that if the install fails we can unpublish
- INSTALL_RESULT=0
- if [[ $PUBLISH_BINARY == true ]]; then INSTALL_RESULT=$(npm install --fallback-to-build=false > /dev/null)$? || true; fi
# if install returned non zero (errored) then we first unpublish and then call false so travis will bail at this line
- if [[ $INSTALL_RESULT != 0 ]]; then echo "returned $INSTALL_RESULT";node-pre-gyp unpublish;false; fi
# If success then we arrive here so lets clean up
- node-pre-gyp clean
