language: cpp

addons:
  apt:
    packages:
      - gdb

sudo: required

matrix:
  include:
     # Linux
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.12.0"
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.10.36"
     # OS X
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.12.0"
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.10.36"

env:
  global:
   - JOBS: "12"
   # commented to test OSRM latest
   - OSRM_RELEASE: "v4.6.0"
   - secure: KitzGZjoDblX/3heajcvssGz0JnJ/k02dr2tu03ksUV+6MogC3RSQudqyKY57+f8VyZrcllN/UOlJ0Q/3iG38Oz8DljC+7RZxtkVmE1SFBoOezKCdhcvWM12G3uqPs7hhrRxuUgIh0C//YXEkulUrqa2H1Aj2xeen4E3FAqEoy0=
   - secure: WLGmxl6VTVWhXGm6X83GYNYzPNsvTD+9usJOKM5YBLAdG7cnOBQBNiCCUKc9OZMMZVUr3ec2/iigakH5Y8Yc+U6AlWKzlORyqWLuk4nFuoedu62x6ocQkTkuOc7mHiYhKd21xTGMYauaZRS6kugv4xkpGES2UjI2T8cjZ+LN2jU=

before_install:
- scripts/validate_tag.sh
- source ./scripts/install_node.sh ${NODE_VERSION}

install:
- ulimit -c
- source ./bootstrap.sh
- npm install --build-from-source --clang=1 --verbose --debug

before_script:
- ulimit -c unlimited -S

script:
- ./scripts/publish.sh
- RESULT=0
- make test || RESULT=$?
- for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
- if [[ ${RESULT} != 0 ]]; then exit $RESULT; fi
