language: cpp

sudo: false

matrix:
  include:
     # Linux
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.12.0"
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.10.36"
     # OS X
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.12.0"
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.10.36"

env:
  global:
   - JOBS: "8"
   #- OSRM_RELEASE: "v4.5.0"
   - secure: KitzGZjoDblX/3heajcvssGz0JnJ/k02dr2tu03ksUV+6MogC3RSQudqyKY57+f8VyZrcllN/UOlJ0Q/3iG38Oz8DljC+7RZxtkVmE1SFBoOezKCdhcvWM12G3uqPs7hhrRxuUgIh0C//YXEkulUrqa2H1Aj2xeen4E3FAqEoy0=
   - secure: WLGmxl6VTVWhXGm6X83GYNYzPNsvTD+9usJOKM5YBLAdG7cnOBQBNiCCUKc9OZMMZVUr3ec2/iigakH5Y8Yc+U6AlWKzlORyqWLuk4nFuoedu62x6ocQkTkuOc7mHiYhKd21xTGMYauaZRS6kugv4xkpGES2UjI2T8cjZ+LN2jU=

before_install:
- scripts/validate_tag.sh
- source ./scripts/install_node.sh ${NODE_VERSION}

install:
- source ./bootstrap.sh
- npm install --build-from-source --clang=1

before_script:
- make test

script:
- ./scripts/publish.sh
